Month 9/step 2
NikitaBolschakov/react-burger pull request #6
Opened 2022-12-29 11:23 UTC by NikitaBolschakov

2022-12-29 11:58 UTC, andryxxa93 requested changes
Хороший проект. Всё работает корректно. Видно, что с сокет соединениями вы разобрались. Есть только одно замечание, которое необходимо исправить чтобы работа была принята - 
- Необходимо чтобы при открытии именно "Ленты закзаов" и "Истории заказов" сокет соединение открывалось. То же касается и закрытия сокет соединения - сразу же как эти страницы были покинуты. Сейчас у вас открывается сокет соединение при открытии страницы профиля, хотя должно "Истории заказов".

2022-12-29 11:58 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  const openOrderDetails = useSelector(
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2022-12-29 11:58 UTC, andryxxa93 commented on src/components/pages/reset-password/reset-password.jsx
> +  }
**Можно лучше**

здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2022-12-29 21:39 UTC, NikitaBolschakov commented on src/components/app/app.jsx
> +  const openOrderDetails = useSelector(
Сделано

2022-12-29 21:39 UTC, NikitaBolschakov commented on src/components/pages/reset-password/reset-password.jsx
> +  }
Сделано

2022-12-30 09:20 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-01-20 13:06 UTC, merged